### ISSUE TITLE
Work?

### ISSUE THREAD

**Issue by JoshuaPoirier** [TheLab-ms/tap#1]
What work needs to be done?

**Comment by BillGee1** [comment]
This is my To Do list:

allow more than one text string at a time

finish implementing learn mode

finish implementing packet forwarding
    duplicate packets are not only a forwarding problem, but also an accepting problem.
    For example, send Set Text.  Unit (1,1) gets two copies and should only honor one of them.

implement smarter flash memory usage management

design and implement font system

continue work on technical reference document

do final determination of frame rate

do fine tuning of the baud rate

create more demo apps

of course, lots of testing

The first one is almost done.

The team has other needs, such as the GUI app on a computer to talk to the TAP via USB.  Don did the original with Visual Studio; it is only for Windows.  Such an app needs more functionality and it would be nice if it was on Linux and MacOS as well.

Bill

**Comment by donpowrie** [comment]
As suspected, the problem with the 2 bad boards was a solder bridge between
two of the header pins.  Pics attached.  These have been repaired and I'll
bring them back tonight.

In production these headers will be soldered by reflow after pick-n-place
so this will not happen...

Regards,

Don Powrie
DLP Design, Inc.
don@dlpdesign.com
www.dlpdesign.com

**Comment by donpowrie** [comment]
-----Original Message-----

> From: Don Powrie don@dlpdesign.com
> Sent: Jul 28, 2016 9:14 AM
> To: TheLab-ms/tap reply@reply.github.com, tapthelab@googlegroups.com, William Gee Jr deiresearch@earthlink.net
> Cc: TheLab-ms/tap tap@noreply.github.com
> Subject: [TAP] solder bridges
> 
> As suspected, the problem with the 2 bad boards was a solder bridge between
> two of the header pins.  Pics attached.  These have been repaired and I'll
> bring them back tonight.
> 
> In production these headers will be soldered by reflow after pick-n-place
> so this will not happen...

Pat and I each have another with the same problem.

We may want to test the rest of them: it may be as simple as plugging another unit into it and applying power; no need to program it first.

Bill
